server:
  port: 8081
spring:
  application:
    name: rabbitmq_proder
  rabbitmq:
    host: 192.168.13.128
    port: 5672
    username: guest
    password: guest
    # 确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    # 确认消息已发送到队列(queue)
    publisher-returns: true